Random Seed: 7587
rotation: -22.5-22.5 degree
scale: 10.0%-50.0%
train dataloader: 50000 are ready from D:datasets\imagenet\val
validate dataloader: 1281167 are ready from D:datasets\imagenet\train
loaded model densenet201 has 89.96% of accuracy to original, and 0.06% of accuracy to target 859
start train patches with 100000 data iterations of trainset
start validate patches with 5000 data iterations of validation set
error occured: Traceback (most recent call last):
  File "main.py", line 53, in <module>
    patch.measure_attackCapability(classifier=classifier, eot_dict=EOT_FACTORS, iteration=args.iter_val)
  File "C:\Users\PresentJay\Desktop\Projects\Adversarial_Patch_Attack_With_Pytorch\src\patches.py", line 138, in measure_attackCapability
    output = classifier.model(patched_images)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\densenet.py", line 216, in forward
    features = self.features(x)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\densenet.py", line 127, in forward
    new_features = layer(features)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\densenet.py", line 92, in forward
    bottleneck_output = self.bn_function(prev_features)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\densenet.py", line 53, in bn_function
    bottleneck_output = self.conv1(self.relu1(self.norm1(concated_features)))  # noqa: T484
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 8.00 GiB total capacity; 4.72 GiB already allocated; 16.82 MiB free; 4.93 GiB reserved in total by PyTorch)

