Random Seed: 3241
rotation: -22.5-22.5 degree
scale: 10.0%-50.0%
train dataloader: 50000validate dataloader: 1281167batch size: 40
loaded model resnet50 has 87.52% of accuracy to original, and 0.10% of accuracy to target 859
start train patches with 100000 data iterations of trainset
start validate patches with 5000 data iterations of validation set
error occured during training patch: Traceback (most recent call last):
  File "main.py", line 55, in <module>
    patch.measure_attackCapability(classifier=classifier, eot_dict=EOT_FACTORS, iteration=args.iter_val)
  File "C:\Users\PresentJay\Desktop\Projects\Adversarial_Patch_Attack_With_Pytorch\src\patches.py", line 140, in measure_attackCapability
    output = classifier.model(patched_images)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\resnet.py", line 237, in _forward_impl
    x = self.layer1(x)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\resnet.py", line 129, in forward
    out = self.bn2(out)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\batchnorm.py", line 140, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\functional.py", line 2150, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 8.00 GiB total capacity; 4.73 GiB already allocated; 0 bytes free; 4.88 GiB reserved in total by PyTorch)

