Random Seed: 9221
rotation: -22.5-22.5 degree
scale: 10.0%-50.0%
train dataloader: 50000validate dataloader: 1281167batch size: 50
loaded model resnet50 has 88.24% of accuracy to original, and 0.06% of accuracy to target 859
start train patches with 100000 data iterations of trainset
start validate patches with 5000 data iterations of validation set
error occured: Traceback (most recent call last):
  File "main.py", line 55, in <module>
    patch.measure_attackCapability(classifier=classifier, eot_dict=EOT_FACTORS, iteration=args.iter_val)
  File "C:\Users\PresentJay\Desktop\Projects\Adversarial_Patch_Attack_With_Pytorch\src\patches.py", line 138, in measure_attackCapability
    output = classifier.model(patched_images)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torchvision\models\resnet.py", line 235, in _forward_impl
    x = self.maxpool(x)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\modules\pooling.py", line 164, in forward
    self.return_indices)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\_jit_internal.py", line 365, in fn
    return if_false(*args, **kwargs)
  File "C:\Users\PresentJay\.conda\envs\posepatch\lib\site-packages\torch\nn\functional.py", line 659, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 8.00 GiB total capacity; 4.66 GiB already allocated; 0 bytes free; 4.81 GiB reserved in total by PyTorch)

